---
title: "README"
author: "Student No. 1336616"
date: "06/12/2022"
output: 
  html_document:
    theme: united
---
# Q4PenguinsAssignmentMT22

This is my answer to question 4 of the reproducible research assignment question for MBIOL year 3. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modelling the relationship between body mass and culmen depth in Gentoo Penguins

The attached report (RMD file) will guide you step-by-step through data visualisation for the Palmer Penguins dataset. The report will contain information on how to load in the relevant functions and data, clean the data, make a model, run a statistical test, create a figure for the model, and save it appropriately. 

Ultimately, the relationship between body mass and culmen depth will be modelled using ANOVA for the Gentoo species of penguin from the dataset.  

Files should appear as below:

- penguin-assessment/
    - data_raw/
        - penguins_raw.csv
    - data_clean/
        - penguins_clean.csv
    - functions/
        - libraries.r
        - cleaning.r
        - plotting.r
    - other-outputs/
        - ANOVA-summary.txt
        - linear-regression-summary.txt
        - package-versions.txt
    - src
        - penguin_analysis.rmd
    - README.rmd

Credits to Lydia France for the original tutorial for this, found at [LFrancePenguinProject](https://github.com/LydiaFrance/PenguinProject) 
